imports:
    - { resource: parameters/app.yml }
    - { resource: security.yml }

    - { resource: bundles/doctrine_migrations.yml }
    - { resource: bundles/fos_user.yml }
    - { resource: bundles/fos_rest.yml }
    - { resource: bundles/nelmio_api_doc.yml }